# Generated by Django 5.0.6 on 2024-06-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imgage',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
