# Generated by Django 5.0.6 on 2024-06-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_rename_imgage_product_image_remove_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='imgage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='imgage',
            new_name='image',
        ),
    ]
