# Generated by Django 5.0.6 on 2024-07-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_type',
            field=models.CharField(default='Organic', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.IntegerField(default=1),
        ),
    ]
