# Generated by Django 5.0.6 on 2024-07-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_product_p_type_product_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disclaimer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
